// Roma: misma partida que Barcelona (precios, grupos y cartas con los mismos efectos),
// con barrios, cartas y curiosidades romanas.
import type { CityInfo, CityStrings } from './types'

/** Nombres de las casillas (índice del tablero → nombre) */
const TILES: Record<number, string> = {
  1: 'Tor Bella Monaca',
  3: 'Quarticciolo',
  5: 'Roma Termini',
  6: 'San Lorenzo',
  8: 'Pigneto',
  9: 'Ostiense',
  11: 'Testaccio',
  12: 'Metro di Roma',
  13: 'Garbatella',
  14: 'Monteverde',
  15: 'Roma Tiburtina',
  16: 'Trastevere',
  18: 'Monti',
  19: 'San Giovanni',
  21: 'Prati',
  23: 'Esquilino',
  24: 'Celio',
  25: 'Porto di Civitavecchia',
  26: "Campo de' Fiori",
  27: 'Piazza Navona',
  28: 'Acquedotti di Roma',
  29: 'Pantheon',
  31: 'Aventino',
  32: 'Parioli',
  34: 'Via Veneto',
  35: 'Aeroporto di Fiumicino',
  37: 'Piazza di Spagna',
  39: 'Via Condotti',
}

const tileNames: CityStrings = Object.fromEntries(Object.entries(TILES).map(([i, n]) => [`tname.${i}`, n]))

/** Datos curiosos: mismas claves que Barcelona, contenido romano */
const FACTS_ES: CityStrings = {
  'fact.nouBarris': 'Debe su nombre a una torre medieval que aún se conserva en el barrio.',
  'fact.santAndreu': 'Es una de las «borgate» levantadas en los años cuarenta en la periferia este.',
  'fact.estacioSants': 'Su nombre no viene de «terminal», sino de las cercanas Termas de Diocleciano.',
  'fact.sants': 'Sufrió de lleno el bombardeo aliado del 19 de julio de 1943; hoy es el barrio universitario.',
  'fact.horta': 'Pier Paolo Pasolini rodó aquí parte de «Accattone» (1961).',
  'fact.poblenou': 'Su antigua central eléctrica Montemartini es hoy un museo con estatuas clásicas entre máquinas.',
  'fact.raval': 'El Monte Testaccio es una colina artificial hecha con millones de ánforas rotas de época romana.',
  'fact.metro': 'Cada vez que se excava una línea nueva aparecen restos arqueológicos que retrasan las obras.',
  'fact.barceloneta': 'Barrio jardín de los años veinte, famoso por sus patios comunitarios, los «lotti».',
  'fact.gracia': 'A su lado está Villa Doria Pamphilj, uno de los parques más grandes de Roma.',
  'fact.estacioFranca': 'Es la gran estación de la alta velocidad en el este de la ciudad.',
  'fact.poblesec': 'Su nombre significa «al otro lado del Tíber».',
  'fact.santAntoni': 'Es el barrio más antiguo de Roma: en época imperial era la Suburra, un barrio popular.',
  'fact.born': 'La basílica de San Juan de Letrán es la catedral de Roma, y no San Pedro.',
  'fact.lesCorts': 'Se construyó después de 1870 sobre antiguos prados junto al Vaticano; de ahí su nombre.',
  'fact.santGervasi': 'En su Piazza Vittorio se conserva la «Puerta Mágica», una puerta alquímica del siglo XVII.',
  'fact.sarria': 'Es una de las siete colinas de Roma, a dos pasos del Coliseo.',
  'fact.port': 'Es el puerto de cruceros de Roma, a unos 70 km de la ciudad.',
  'fact.rambla': 'Giordano Bruno fue quemado aquí en 1600; su estatua preside la plaza.',
  'fact.ramblaCatalunya': 'Conserva la forma alargada del estadio de Domiciano sobre el que se construyó.',
  'fact.aigues': 'Las «nasoni», fuentes de hierro de la calle, dan agua potable gratis desde 1874.',
  'fact.placaCatalunya': 'Su cúpula de hormigón sin armar sigue siendo la más grande de su tipo en el mundo.',
  'fact.diagonal': 'Por la cerradura de la Orden de Malta se ve la cúpula de San Pedro perfectamente enmarcada.',
  'fact.quadratOr': 'Barrio elegante junto a Villa Borghese, lleno de villas y embajadas.',
  'fact.tibidabo': 'Fue el escenario de «La dolce vita» de Federico Fellini (1960).',
  'fact.aeroport': 'Su nombre oficial es Aeropuerto Leonardo da Vinci.',
  'fact.pedralbes': 'Su escalinata de 135 escalones se inauguró en 1725.',
  'fact.passeigGracia': 'Su nombre viene de los conductos que llevaban agua a las Termas de Agripa.',
}

const FACTS_CA: CityStrings = {
  'fact.nouBarris': 'Deu el nom a una torre medieval que encara es conserva al barri.',
  'fact.santAndreu': 'És una de les «borgate» aixecades als anys quaranta a la perifèria est.',
  'fact.estacioSants': 'El nom no ve de «terminal», sinó de les properes Termes de Dioclecià.',
  'fact.sants': 'Va patir de ple el bombardeig aliat del 19 de juliol de 1943; avui és el barri universitari.',
  'fact.horta': 'Pier Paolo Pasolini hi va rodar part d’«Accattone» (1961).',
  'fact.poblenou': 'La seva antiga central elèctrica Montemartini és avui un museu amb estàtues clàssiques entre màquines.',
  'fact.raval': 'El Monte Testaccio és un turó artificial fet amb milions d’àmfores trencades d’època romana.',
  'fact.metro': 'Cada cop que s’excava una línia nova apareixen restes arqueològiques que endarrereixen les obres.',
  'fact.barceloneta': 'Barri jardí dels anys vint, famós pels seus patis comunitaris, els «lotti».',
  'fact.gracia': 'Al seu costat hi ha Villa Doria Pamphilj, un dels parcs més grans de Roma.',
  'fact.estacioFranca': 'És la gran estació de l’alta velocitat a l’est de la ciutat.',
  'fact.poblesec': 'El seu nom vol dir «a l’altra banda del Tíber».',
  'fact.santAntoni': 'És el barri més antic de Roma: en època imperial era la Suburra, un barri popular.',
  'fact.born': 'La basílica de Sant Joan del Laterà és la catedral de Roma, i no Sant Pere.',
  'fact.lesCorts': 'Es va construir després de 1870 sobre antics prats al costat del Vaticà; d’aquí el nom.',
  'fact.santGervasi': 'A la seva Piazza Vittorio es conserva la «Porta Màgica», una porta alquímica del segle XVII.',
  'fact.sarria': 'És un dels set turons de Roma, a dos passos del Colosseu.',
  'fact.port': 'És el port de creuers de Roma, a uns 70 km de la ciutat.',
  'fact.rambla': 'Giordano Bruno hi va ser cremat el 1600; la seva estàtua presideix la plaça.',
  'fact.ramblaCatalunya': 'Conserva la forma allargada de l’estadi de Domicià sobre el qual es va construir.',
  'fact.aigues': 'Les «nasoni», fonts de ferro del carrer, donen aigua potable gratis des de 1874.',
  'fact.placaCatalunya': 'La seva cúpula de formigó sense armar encara és la més gran del seu tipus al món.',
  'fact.diagonal': 'Pel pany de l’Orde de Malta es veu la cúpula de Sant Pere perfectament emmarcada.',
  'fact.quadratOr': 'Barri elegant al costat de Villa Borghese, ple de vil·les i ambaixades.',
  'fact.tibidabo': 'Va ser l’escenari de «La dolce vita» de Federico Fellini (1960).',
  'fact.aeroport': 'El seu nom oficial és Aeroport Leonardo da Vinci.',
  'fact.pedralbes': 'La seva escalinata de 135 graons es va inaugurar el 1725.',
  'fact.passeigGracia': 'El seu nom ve dels conductes que portaven aigua a les Termes d’Agripa.',
}

/** Cartas: mismos efectos que en Barcelona (avanzar a la casilla 25, cobrar 150 €…) */
const CARDS_ES: CityStrings = {
  'card.s01': 'Te invitan a un crucero: avanza hasta el Porto di Civitavecchia.',
  'card.s02': 'A tu bici compartida se le sale la cadena: retrocede 3 casillas.',
  'card.s03': 'Quedas frente al Altar de la Patria: avanza hasta Piazza Venezia (SALIDA).',
  'card.s04': 'Día de compras: avanza hasta Via Condotti.',
  'card.s05': 'Paseo por la colina: avanza hasta el Celio.',
  'card.s06': 'Antojo de carbonara en el Testaccio: avanza hasta allí.',
  'card.s07': 'Huelga de transporte («sciopero»): ve al transporte más cercano. Si tiene dueño, paga el doble.',
  'card.s08': 'Se va la luz en el metro: ve al servicio más cercano. Si tiene dueño, paga 10 veces los dados.',
  'card.s09': 'Te pillan con la Vespa dentro de la ZTL: ve directo al atasco del GRA.',
  'card.s10': 'Sales del GRA sin esperar. Guárdala hasta que la necesites.',
  'card.s11': 'Te cobran un «coperto» carísimo en Piazza Navona: paga 50 €.',
  'card.s12': 'Te toca un premio de la Lotteria Italia: cobra 150 €.',
  'card.s13': 'Inspección técnica del edificio: paga 25 € por casa y 100 € por hotel.',
  'card.s14': 'Aparcas la Vespa en doble fila: multa de 15 €.',
  'card.s15': 'Invitas a todos a un aperitivo en Trastevere: paga 50 € a cada jugador.',
  'card.s16': 'Te escapas en tren: avanza hasta Roma Termini.',
  'card.f01': 'Tu foto con un centurión se hace viral: cobra 100 €.',
  'card.f02': 'Natale di Roma, 21 de abril: invitas a supplì, paga 20 € a cada jugador.',
  'card.f03': 'Organizas una «pizzata»: cada jugador te paga 10 € por su porción.',
  'card.f04': 'Hacienda se equivoca a tu favor: cobra 200 €.',
  'card.f05': 'Entradas para el derbi en el Estadio Olímpico: paga 50 €.',
  'card.f06': 'Vendes antigüedades en el mercadillo de Porta Portese: cobra 50 €.',
  'card.f07': 'Un amigo en Vespa te saca del GRA: sales sin esperar. Guárdala.',
  'card.f08': 'Vas a la playa de Ostia un domingo de agosto: ve directo al atasco del GRA.',
  'card.f09': 'Corres la maratón de Roma: avanza hasta Piazza Venezia (SALIDA).',
  'card.f10': 'Ganas el concurso de tiramisú del barrio: cobra 20 €.',
  'card.f11': 'Curso de cocina romana con chef: paga 100 €.',
  'card.f12': 'Vendes la viña del abuelo en los Castelli Romani: cobra 100 €.',
  'card.f13': 'Tu balcón gana el premio de flores del barrio: cobra 25 €.',
  'card.f14': 'Derrama del «condominio»: paga 40 € por casa y 115 € por hotel.',
  'card.f15': 'Una gaviota te roba el bocadillo y te mancha la camisa: tintorería, paga 50 €.',
  'card.f16': 'Encuentras un billete en la escalinata de Piazza di Spagna: cobra 10 €.',
}

const CARDS_CA: CityStrings = {
  'card.s01': 'Et conviden a un creuer: avança fins al Porto di Civitavecchia.',
  'card.s02': 'A la teva bici compartida se li surt la cadena: retrocedeix 3 caselles.',
  'card.s03': 'Quedes davant l’Altar de la Pàtria: avança fins a Piazza Venezia (SORTIDA).',
  'card.s04': 'Dia de compres: avança fins a Via Condotti.',
  'card.s05': 'Passeig pel turó: avança fins al Celio.',
  'card.s06': 'Et ve de gust una carbonara al Testaccio: avança fins allà.',
  'card.s07': 'Vaga de transport («sciopero»): ves al transport més proper. Si té amo, paga el doble.',
  'card.s08': 'Se’n va la llum al metro: ves al servei més proper. Si té amo, paga 10 vegades els daus.',
  'card.s09': 'T’enxampen amb la Vespa dins la ZTL: ves directe a l’embús del GRA.',
  'card.s10': 'Surts del GRA sense esperar. Guarda-la fins que la necessitis.',
  'card.s11': 'Et cobren un «coperto» caríssim a Piazza Navona: paga 50 €.',
  'card.s12': 'Et toca un premi de la Lotteria Italia: cobra 150 €.',
  'card.s13': 'Inspecció tècnica de l’edifici: paga 25 € per casa i 100 € per hotel.',
  'card.s14': 'Aparques la Vespa en doble filera: multa de 15 €.',
  'card.s15': 'Convides tothom a un aperitiu al Trastevere: paga 50 € a cada jugador.',
  'card.s16': 'T’escapes en tren: avança fins a Roma Termini.',
  'card.f01': 'La teva foto amb un centurió es fa viral: cobra 100 €.',
  'card.f02': 'Natale di Roma, 21 d’abril: convides a supplì, paga 20 € a cada jugador.',
  'card.f03': 'Organitzes una «pizzata»: cada jugador et paga 10 € per la seva porció.',
  'card.f04': 'Hisenda s’equivoca a favor teu: cobra 200 €.',
  'card.f05': 'Entrades per al derbi a l’Estadi Olímpic: paga 50 €.',
  'card.f06': 'Vens antiguitats al mercat de Porta Portese: cobra 50 €.',
  'card.f07': 'Un amic en Vespa et treu del GRA: surts sense esperar. Guarda-la.',
  'card.f08': 'Vas a la platja d’Ostia un diumenge d’agost: ves directe a l’embús del GRA.',
  'card.f09': 'Corres la marató de Roma: avança fins a Piazza Venezia (SORTIDA).',
  'card.f10': 'Guanyes el concurs de tiramisú del barri: cobra 20 €.',
  'card.f11': 'Curs de cuina romana amb xef: paga 100 €.',
  'card.f12': 'Vens la vinya de l’avi als Castelli Romani: cobra 100 €.',
  'card.f13': 'El teu balcó guanya el premi de flors del barri: cobra 25 €.',
  'card.f14': 'Derrama del «condominio»: paga 40 € per casa i 115 € per hotel.',
  'card.f15': 'Una gavina et roba l’entrepà i et taca la camisa: tintoreria, paga 50 €.',
  'card.f16': 'Trobes un bitllet a l’escalinata de Piazza di Spagna: cobra 10 €.',
}

/** Esquinas, mazos, impuestos, fichas y frases que mencionan la «cárcel» */
const UI_ES: CityStrings = {
  'app.title': 'Roma Tycoon',
  'app.tagline': 'Compra Roma, barrio a barrio',
  'tile.go': 'SALIDA · Piazza Venezia',
  'tile.jail': 'Atasco en el GRA (Grande Raccordo Anulare)',
  'tile.parking': 'Siesta en Villa Borghese',
  'tile.goToJail': '¡Multa de la ZTL, zona de tráfico limitado!',
  'tile.touristTax': 'Tassa di soggiorno',
  'tile.ibi': 'IMU',
  'short.jail': 'GRA',
  'short.parking': 'Villa Borghese',
  'short.goToJail': 'ZTL',
  'short.sorpresa': 'Sorpresa',
  'short.festa': 'Dolce Vita',
  'deck.sorpresa': 'Sorpresa Roma',
  'deck.festa': 'Dolce Vita',
  'token.sagrada': 'Coliseo',
  'token.patinete': 'Vespa',
  'token.gaviota': 'Gaviota',
  'token.tranvia': 'Tranvía',
  'token.castell': 'Helado',
  'token.panot': 'Sampietrino',
  'jail.status': 'Estás en el atasco del GRA. Te quedan {tries} intentos para sacar dobles.',
  'trade.jailCards': '{n} carta(s) de salir del GRA',
  'players.inJail': 'En el GRA',
  'tile.goToJailInfo': '¡Multa! Vas directo al atasco del GRA sin cobrar la SALIDA.',
  'rules.turn': 'Tira dos dados y avanza. Con dobles repites; con 3 dobles seguidos vas al atasco del GRA. Al pasar por la SALIDA cobras 200 €.',
  'rules.jail': 'Para salir del GRA: paga 50 €, saca dobles (3 intentos) o usa la carta. Al tercer fallo pagas 50 € y sales.',
  'reason.notInJail': 'No estás en el GRA.',
  'log.parking': '{name} se echa una siesta en Villa Borghese.',
  'log.visitJail': '{name} pasa junto al GRA sin problemas.',
  'log.goToJail': '{name} se queda atascado en el GRA.',
  'log.jailOutDoubles': '¡{name} saca dobles y sale del GRA!',
  'log.jailPaid': '{name} paga {amount} y sale del GRA.',
  'log.jailCard': '{name} usa su carta y sale del GRA.',
  'landing.goToJail': '¡Multa! {name} va al GRA',
  'landing.visit': '{name} pasa por el GRA de visita',
  'jail.title': 'Atascado en el GRA',
  'sound.jail': 'Al GRA',
  'online.shareText': '¡Juega conmigo a Roma Tycoon! Código de sala: {code}',
}

const UI_CA: CityStrings = {
  'app.title': 'Roma Tycoon',
  'app.tagline': 'Compra Roma, barri a barri',
  'tile.go': 'SORTIDA · Piazza Venezia',
  'tile.jail': 'Embús al GRA (Grande Raccordo Anulare)',
  'tile.parking': 'Migdiada a Villa Borghese',
  'tile.goToJail': 'Multa de la ZTL, zona de trànsit limitat!',
  'deck.sorpresa': 'Sorpresa Roma',
  'deck.festa': 'Dolce Vita',
  'token.sagrada': 'Colosseu',
  'token.patinete': 'Vespa',
  'token.gaviota': 'Gavina',
  'token.tranvia': 'Tramvia',
  'token.castell': 'Gelat',
  'token.panot': 'Sampietrino',
  'jail.status': 'Ets a l’embús del GRA. Et queden {tries} intents per treure dobles.',
  'trade.jailCards': '{n} carta/es de sortir del GRA',
  'players.inJail': 'Al GRA',
  'tile.goToJailInfo': 'Multa! Vas directe a l’embús del GRA sense cobrar la SORTIDA.',
  'rules.turn': 'Tira dos daus i avança. Amb dobles repeteixes; amb 3 dobles seguits vas a l’embús del GRA. En passar per la SORTIDA cobres 200 €.',
  'rules.jail': 'Per sortir del GRA: paga 50 €, treu dobles (3 intents) o fes servir la carta. Al tercer error pagues 50 € i surts.',
  'reason.notInJail': 'No ets al GRA.',
  'log.parking': '{name} fa la migdiada a Villa Borghese.',
  'log.visitJail': '{name} passa pel GRA sense problemes.',
  'log.goToJail': '{name} queda encallat al GRA.',
  'log.jailOutDoubles': '{name} treu dobles i surt del GRA!',
  'log.jailPaid': '{name} paga {amount} i surt del GRA.',
  'log.jailCard': '{name} fa servir la carta i surt del GRA.',
  'landing.goToJail': 'Multa! {name} va al GRA',
  'landing.visit': '{name} passa pel GRA de visita',
  'jail.title': 'Encallat al GRA',
  'sound.jail': 'Al GRA',
  'online.shareText': 'Juga amb mi a Roma Tycoon! Codi de sala: {code}',
}

export const ROMA: CityInfo = {
  id: 'roma',
  name: 'Roma',
  country: 'Italia',
  flag: '🇮🇹',
  available: true,
  colors: { from: '#C2512E', to: '#6E2414', accent: '#F2C14E' },
  strings: {
    es: { ...tileNames, ...FACTS_ES, ...CARDS_ES, ...UI_ES },
    ca: { ...tileNames, ...FACTS_CA, ...CARDS_CA, ...UI_CA },
  },
}
